import type { Character } from './types';

export const mockCharacters: Character[] = [
  {
    id: '1',
    name: 'Harry Potter',
    house: 'Gryffindor',
    species: 'Human',
    gender: 'Male',
    image: 'https://example.com/harry.jpg',
    born: '31 July 1980',
    died: null,
    blood_status: 'Half-blood',
    nationality: 'British',
    patronus: 'Stag',
    wands: ['Holly, 11", Phoenix feather'],
    jobs: ['Head of Auror Office'],
    alias_names: ['The Boy Who Lived', 'Undesirable No. 1'],
    wiki: 'https://harrypotter.fandom.com/wiki/Harry_Potter',
  },
  {
    id: '2',
    name: 'Hermione Granger',
    house: 'Gryffindor',
    species: 'Human',
    gender: 'Female',
    image: 'https://example.com/hermione.jpg',
    born: '19 September 1979',
    died: null,
    blood_status: 'Muggle-born',
    nationality: 'British',
    patronus: 'Otter',
    wands: ['Vine wood, 10¾", Dragon heartstring'],
    jobs: ['Minister for Magic'],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Hermione_Granger',
  },
  {
    id: '3',
    name: 'Ron Weasley',
    house: 'Gryffindor',
    species: 'Human',
    gender: 'Male',
    image: 'https://example.com/ron.jpg',
    born: '1 March 1980',
    died: null,
    blood_status: 'Pure-blood',
    nationality: 'British',
    patronus: 'Jack Russell Terrier',
    wands: ['Willow, 14", Unicorn hair'],
    jobs: ['Auror'],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Ron_Weasley',
  },
  {
    id: '4',
    name: 'Draco Malfoy',
    house: 'Slytherin',
    species: 'Human',
    gender: 'Male',
    image: 'https://example.com/draco.jpg',
    born: '5 June 1980',
    died: null,
    blood_status: 'Pure-blood',
    nationality: 'British',
    patronus: null,
    wands: ['Hawthorn, 10", Unicorn hair'],
    jobs: [],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Draco_Malfoy',
  },
  {
    id: '5',
    name: 'Luna Lovegood',
    house: 'Ravenclaw',
    species: 'Human',
    gender: 'Female',
    image: 'https://example.com/luna.jpg',
    born: '13 February 1981',
    died: null,
    blood_status: 'Pure-blood',
    nationality: 'British',
    patronus: 'Hare',
    wands: [],
    jobs: ['Magizoologist'],
    alias_names: ['Loony Lovegood'],
    wiki: 'https://harrypotter.fandom.com/wiki/Luna_Lovegood',
  },
  {
    id: '6',
    name: 'Severus Snape',
    house: 'Slytherin',
    species: 'Human',
    gender: 'Male',
    image: 'https://example.com/snape.jpg',
    born: '9 January 1960',
    died: '2 May 1998',
    blood_status: 'Half-blood',
    nationality: 'British',
    patronus: 'Doe',
    wands: [],
    jobs: ['Potions master', 'Headmaster of Hogwarts'],
    alias_names: ['Half-Blood Prince'],
    wiki: 'https://harrypotter.fandom.com/wiki/Severus_Snape',
  },
  {
    id: '7',
    name: 'Albus Dumbledore',
    house: 'Gryffindor',
    species: 'Human',
    gender: 'Male',
    image: 'https://example.com/dumbledore.jpg',
    born: 'August 1881',
    died: '1997',
    blood_status: 'Half-blood',
    nationality: 'British',
    patronus: 'Phoenix',
    wands: ['Elder wand'],
    jobs: ['Headmaster of Hogwarts'],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Albus_Dumbledore',
  },
  {
    id: '8',
    name: 'Minerva McGonagall',
    house: 'Gryffindor',
    species: 'Human',
    gender: 'Female',
    image: 'https://example.com/mcgonagall.jpg',
    born: '4 October 1935',
    died: null,
    blood_status: 'Half-blood',
    nationality: 'British',
    patronus: 'Cat',
    wands: ['Fir, 9½", Dragon heartstring'],
    jobs: ['Head of Gryffindor', 'Transfiguration professor', 'Headmistress'],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Minerva_McGonagall',
  },
  {
    id: '9',
    name: 'Rubeus Hagrid',
    house: 'Gryffindor',
    species: 'Half-giant',
    gender: 'Male',
    image: 'https://example.com/hagrid.jpg',
    born: '6 December 1928',
    died: null,
    blood_status: 'Half-blood',
    nationality: 'British',
    patronus: null,
    wands: ['Oak, 16", Unicorn hair (broken)'],
    jobs: ['Keeper of Keys and Grounds', 'Care of Magical Creatures professor'],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Rubeus_Hagrid',
  },
  {
    id: '10',
    name: 'Bellatrix Lestrange',
    house: 'Slytherin',
    species: 'Human',
    gender: 'Female',
    image: 'https://example.com/bellatrix.jpg',
    born: '1951',
    died: '2 May 1998',
    blood_status: 'Pure-blood',
    nationality: 'British',
    patronus: null,
    wands: ['Walnut, 12¾", Dragon heartstring'],
    jobs: [],
    alias_names: [],
    wiki: 'https://harrypotter.fandom.com/wiki/Bellatrix_Lestrange',
  },
];
